# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-17 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import shortner.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_kirrurl_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirrurl',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='kirrurl',
            name='url',
            field=models.CharField(max_length=200, validators=[shortner.validators.validate_url]),
        ),
    ]
